In [3]:
seq = ['asasda', 'asasdasdasddasd', 'asd']


In [5]:
l = range(len(seq))

In [6]:
sorted(l, key = lambda x: seq[x])

[0, 1, 2]

In [10]:
import utils
import config
import logging
from data_loader import MTDataset
from torch.utils.data import DataLoader


utils.set_logger(config.log_path)

train_dataset = MTDataset(config.train_data_path)
dev_dataset = MTDataset(config.dev_data_path)
test_dataset = MTDataset(config.test_data_path)
# logging.info(dev_dataset[295][0])
# logging.info(dev_dataset[295][1])
logging.info("-------- Dataset Build! --------")
train_dataloader = DataLoader(train_dataset, shuffle=True, batch_size=config.batch_size,
                                collate_fn=train_dataset.collate_fn)
dev_dataloader = DataLoader(dev_dataset, shuffle=False, batch_size=config.batch_size,
                            collate_fn=dev_dataset.collate_fn)
test_dataloader = DataLoader(test_dataset, shuffle=False, batch_size=config.batch_size,
                                collate_fn=test_dataset.collate_fn)
logging.info("-------- Get Dataloader! --------")

src = 1
batch = 1
tgt = 1
tgt_y = 1
tgt_key_padding_mask = 1
tgt_mask = 1
ntokens = 1


for batch in dev_dataloader:
    src = batch.src
    src_key_padding_mask = batch.src_key_padding_mask
    tgt = batch.tgt
    tgt_y = batch.tgt_y
    tgt_key_padding_mask = batch.tgt_key_padding_mask
    tgt_mask = batch.tgt_mask
    ntokens = batch.ntokens
    break


-------- Dataset Build! --------
-------- Get Dataloader! --------


In [11]:
src[0]

tensor([   2, 2768,    3,    0,    0], device='cuda:0')

In [12]:
src_key_padding_mask[0]

tensor([False, False, False,  True,  True])

In [14]:
src_key_padding_mask.shape

torch.Size([32, 5])

In [23]:
tgt.shape

torch.Size([32, 7])

In [16]:
tgt_y[0]

tensor([15839,     3,     0,     0,     0,     0,     0], device='cuda:0')

In [24]:
tgt_mask

tensor([[ True, False, False, False, False, False, False],
        [ True,  True, False, False, False, False, False],
        [ True,  True,  True, False, False, False, False],
        [ True,  True,  True,  True, False, False, False],
        [ True,  True,  True,  True,  True, False, False],
        [ True,  True,  True,  True,  True,  True, False],
        [ True,  True,  True,  True,  True,  True,  True]], device='cuda:0')

In [18]:
ntokens

tensor(102, device='cuda:0')

In [25]:
tgt_key_padding_mask[31]

tensor([False, False, False, False, False,  True,  True], device='cuda:0')