In [3]:
seq = ['asasda', 'asasdasdasddasd', 'asd']


In [5]:
l = range(len(seq))

In [6]:
sorted(l, key = lambda x: seq[x])

[0, 1, 2]

In [1]:
import utils
import config
import logging
from data_loader import MTDataset
from torch.utils.data import DataLoader


utils.set_logger(config.log_path)

train_dataset = MTDataset(config.train_data_path)
dev_dataset = MTDataset(config.dev_data_path)
test_dataset = MTDataset(config.test_data_path)
# logging.info(dev_dataset[295][0])
# logging.info(dev_dataset[295][1])
logging.info("-------- Dataset Build! --------")
train_dataloader = DataLoader(train_dataset, shuffle=True, batch_size=config.batch_size,
                                collate_fn=train_dataset.collate_fn)
dev_dataloader = DataLoader(dev_dataset, shuffle=False, batch_size=config.batch_size,
                            collate_fn=dev_dataset.collate_fn)
test_dataloader = DataLoader(test_dataset, shuffle=False, batch_size=config.batch_size,
                                collate_fn=test_dataset.collate_fn)
logging.info("-------- Get Dataloader! --------")

src = 1
src_mask = 1
tgt = 1
tgt_y = 1
tgt_mask = 1
ntokens = 1


for batch in dev_dataloader:
    src = batch.src
    src_mask = batch.src_mask
    tgt = batch.tgt
    tgt_y = batch.tgt_y
    tgt_mask = batch.tgt_mask
    ntokens = batch.ntokens
    break


-------- Dataset Build! --------
-------- Get Dataloader! --------


In [2]:
src[0]

tensor([   2, 2768,    3,    0,    0], device='cuda:0')

In [3]:
src_mask[0]

tensor([[ True,  True,  True, False, False]])

In [4]:
src_mask.shape

torch.Size([32, 1, 5])

In [5]:
tgt[0]

tensor([    2, 15839,     3,     0,     0,     0,     0], device='cuda:0')

In [6]:
tgt_y[0]

tensor([15839,     3,     0,     0,     0,     0,     0], device='cuda:0')

In [7]:
tgt_mask[0]

tensor([[ True, False, False, False, False, False, False],
        [ True,  True, False, False, False, False, False],
        [ True,  True,  True, False, False, False, False],
        [ True,  True,  True, False, False, False, False],
        [ True,  True,  True, False, False, False, False],
        [ True,  True,  True, False, False, False, False],
        [ True,  True,  True, False, False, False, False]], device='cuda:0')

In [8]:
ntokens

tensor(102, device='cuda:0')